- name: Install Firefly III using Composer
  command: "composer create-project grumpydictator/firefly-iii --no-interaction --no-dev --prefer-dist firefly-iii {{ firefly_version }}"
  args:
    chdir: /var/www/html
    creates: /var/www/html/firefly-iii

- name: Set folder permissions
  shell: |
    chown -R www-data:www-data /var/www/html/firefly-iii
    chmod -R 777 /var/www/html/firefly-iii/storage

- name: Configure .env file
  lineinfile:
    dest: /var/www/html/firefly-iii/.env
    regexp: "{{item.property}}"
    line: "{{ item.value }}"
  with_items:
    - { property: '^SITE_OWNER=.*', value: 'SITE_OWNER=mikolaj.s.kaczmarek@outlook.com' }
    - { property: '^DEFAULT_LANGUAGE=.*', value: 'DEFAULT_LANGUAGE=pl_PL' }
    - { property: '^DEFAULT_LOCALE=.*', value: 'DEFAULT_LOCALE=pl_PL' }
    - { property: '^TZ=.*', value: 'TZ=Europe/Warsaw' }
    - { property: '^TRUSTED_PROXIES=.*', value: 'TRUSTED_PROXIES=**' }
    - { property: '^DB_HOST=.*', value: 'DB_HOST={{ db_private_ip }}' }
    - { property: '^DB_PASSWORD=.*', value: 'DB_PASSWORD={{firefly_db_user_password}}' }

- name: Install Polish locale
  apt:
    name: language-pack-pl-base

- name: Setup new database
  shell: |
    cd /var/www/html/firefly-iii
    php artisan migrate:refresh --seed
    php artisan firefly-iii:upgrade-database
  when: restore_successful == false
  ignore_errors: true


- name: Setup authentication
  shell: |
    cd /var/www/html/firefly-iii
    php artisan passport:install
    php artisan key:generate
