- name: Add Apache2 repository
  apt_repository:
    repo: ppa:ondrej/apache2
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Disable iptables
  shell: |
    service iptables stop

- name: Allow Load Balancer to access /server-status page
  lineinfile:
    path: /etc/apache2/mods-enabled/status.conf
    regexp: '\#Require ip 192\.0\.2\.0\/24'
    line: Require ip 10.1.1

- name: Configure PHP modules
  shell: |
    a2enmod php8.2
    a2enmod rewrite

- name: Restart Apache2 service
  command: service apache2 restart
