### Databases
- name: Remove test MySQL database
  mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: test
    state: absent

- name: Create the Firefly database
  mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: firefly
    state: present

### Users
- name: Remove anonymous MySQL user
  mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: ''
    state: absent

- name: Create MySQL firefly user
  mysql_user:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: 'firefly'
    password: '{{ firefly_db_user_password }}'
    host: base-vm.basesubnet.basevcn.oraclevcn.com
    priv: 'firefly.*:ALL'
    state: present
  when: firefly_db_user_password is defined

- name: Reload privilege tables
  command: 'mysql -u root -p{{db_root_password}} -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
