- name: Install MySQL 8 repository
  apt:
    name: software-properties-common
    state: present

- name: Import MySQL GPG Key
  apt_key:
    url: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    state: present

- name: Add MySQL APT repository
  apt_repository:
    repo: "deb http://repo.mysql.com/apt/ubuntu/ {{ ansible_distribution_release }} mysql-8.0"
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started

- name: Create MySQL root user with password
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: 'root'
    password: '{{ db_root_password }}'
    host: localhost
    priv: '*.*:ALL,GRANT'
    state: present
  when: db_root_password is defined
  ignore_errors: true

- name: Allow connections from other hosts
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address *= 127\.0\.0\.1'
    line: "bind-address = 0.0.0.0"

- name: Restart MySQL service
  service:
    name: mysql
    state: restarted