- name: Configure prerequisites
  import_tasks: prerequisites.yml

- name: Install mysql
  import_tasks: install_mysql.yml

- name: Configure mysql
  import_tasks: configure_mysql.yml

- name: Try to restore backup
  import_tasks: restore_backup.yml
  ignore_errors: true

- name: Schedule backup
  import_tasks: setup_backup.yml
