- name: Make sure Python and pip are installed
  apt:
    update_cache: yes
    name:
      - python3
      - python3-pip

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Allow HTTP traffic through firewall
  shell: |
    iptables -A INPUT -p tcp --dport 3306 -j ACCEPT
    netfilter-persistent save
    netfilter-persistent reload
    iptables -F
