- name: Make sure Python and pip are installed
  apt:
    update_cache: yes
    name:
      - python3
      - python3-pip

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Disable iptables
  command: service iptables stop