- name: Create config directory
  file:
    path: ~/.oci
    state: directory

- name: Create config file
  template:
    src: templates/config.j2
    dest: ~/.oci/config

- name: Fix file permissions
  command: oci setup repair-file-permissions --file ~/.oci/config

- name: Upload private key
  copy:
    src: "{{ key_file_path }}"
    dest: ~/.oci/oci_api_key.pem
    mode: 0600
