- name: Make sure Python and pip are installed
  apt:
    update_cache: yes
    name:
      - python3
      - python3-pip

- name: Make sure jq and unzip are installed
  apt:
    update_cache: yes
    name:
      - jq
      - unzip
