---
- name: Install PHP and Composer
  hosts: base_instance
  become: true
  gather_facts: no
  tags: apache
  tasks:
    - name: Install EPEL repository for Ubuntu
      apt:
        name:
          - software-properties-common
          - ca-certificates
          - apt-transport-https
        state: present

    - name: Add PHP repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Add Apache2 repository
      apt_repository:
        repo: ppa:ondrej/apache2
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache, PHP and mysql
      apt:
        name:
          - apache2
          - mysql-common
          - php8.2
          - php8.2-common
          - php8.2-bcmath
          - php8.2-intl
          - php8.2-curl
          - php8.2-zip
          - php8.2-gd
          - php8.2-xml
          - php8.2-mbstring
          - php8.2-ldap
          - php8.2-mysql
          - php-mysql
          - curl
        state: present

    - name: Install Composer
      shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"

    - name: Allow HTTP traffic through firewall
      shell: |
        iptables -A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
        iptables -A OUTPUT -p tcp --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT
        netfilter-persistent save
        netfilter-persistent reload
        iptables -F

    - name: Allow Load Balancer to access /server-status page
      lineinfile:
        path: /etc/apache2/mods-enabled/status.conf
        regexp: '\#Require ip 192\.0\.2\.0\/24'
        line: Require ip 10.1.1

    - name: Restart Apache2 service
      command: service apache2 restart


- name: Get Firefly III version
  hosts: base_instance
  gather_facts: no
  tags:
    - firefly
    - importer

  tasks:
    - name: Fetch JSON data
      uri:
        url: https://version.firefly-iii.org/index.json
        return_content: yes
      register: json_response

    - name: Extract Firefly III version
      set_fact:
        raw_firefly_version: "{{ (json_response.content | from_json)['firefly_iii']['stable']['version'] }}"
        raw_data_importer_version: "{{ (json_response.content | from_json)['data']['stable']['version'] }}"

    - name: Remove 'v' prefix from version
      set_fact:
        firefly_version: "{{ raw_firefly_version[1:] }}"
        data_importer_version: "{{ raw_data_importer_version[1:] }}"


- name: Install Firefly III
  hosts: base_instance
  become: true
  gather_facts: no
  tags: firefly
  vars_files:
    - "{{playbook_dir}}/variables/db.yml"

  tasks:
    - name: Install Firefly III using Composer
      command: "composer create-project grumpydictator/firefly-iii --no-interaction --no-dev --prefer-dist firefly-iii {{ firefly_version }}"
      args:
        chdir: /var/www/html
        creates: /var/www/html/firefly-iii

    - name: Set folder permissions
      shell: |
        sudo chown -R www-data:www-data /var/www/html/firefly-iii
        sudo chmod -R 775 /var/www/html/firefly-iii/storage

    - name: Configure .env file
      lineinfile:
        dest: /var/www/html/firefly-iii/.env
        regexp: "{{item.property}}"
        line: "{{ item.value }}"
      with_items:
        - { property: '^SITE_OWNER=.*', value: 'SITE_OWNER=mikolaj.s.kaczmarek@outlook.com' }
        - { property: '^DEFAULT_LANGUAGE=.*', value: 'DEFAULT_LANGUAGE=pl_PL' }
        - { property: '^DEFAULT_LOCALE=.*', value: 'DEFAULT_LOCALE=pl_PL' }
        - { property: '^TZ=.*', value: 'TZ=Europe/Warsaw' }
        - { property: '^DB_HOST=.*', value: 'DB_HOST={{ db_private_ip }}' } #FIXME
        - { property: '^DB_PASSWORD=.*', value: 'DB_PASSWORD={{db_user_password}}' } #FIXME

    - name: Install Polish locale
      apt:
        name: language-pack-pl-base

    - name: Setup Artisian
      shell: |
        cd /var/www/html/firefly-iii
        php artisan migrate:refresh --seed
        php artisan firefly-iii:upgrade-database
        php artisan passport:install
        php artisan key:generate





- name: Install Data Importer
  hosts: base_instance
  become: true
  gather_facts: no
  tags: importer

  tasks:
    - name: Install Data Importer using Composer
      command: "composer create-project firefly-iii/data-importer --no-interaction --no-dev --prefer-dist data-importer {{ data_importer_version }}"
      args:
        chdir: /var/www/html

    - name: Set folder permissions
      shell: |
        sudo chown -R www-data:www-data /var/www/html/data-importer
        sudo chmod -R 775 /var/www/html/data-importer/storage

    - name: Configure .env file
      lineinfile:
        dest: /var/www/html/data-importer/.env
        regexp: "^{{ item.property | regex_escape() }}="
        line: "{{ item.property }}={{ item.value }}"
      with_items:
        - { property: '^FIREFLY_III_URL=.*', value: 'http://firefly.mkaczmarek.com' }
        - { property: '^TZ=.*', value: 'TZ=Europe/Warsaw' }

- name: Configure Apache
  hosts: base_instance
  become: true
  gather_facts: no
  tags: apache_config

  tasks:
    - name: Copy Apache configuration
      copy:
        src: "{{playbook_dir}}/files/firefly-iii/apache2.conf"
        dest: /etc/apache2/apache2.conf

    - name: Copy Apache site configs
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
      with_items:
        - { src: '{{playbook_dir}}/files/firefly-iii/firefly-iii.conf', dest: '/etc/apache2/sites-available/firefly-iii.conf' }
        - { src: '{{playbook_dir}}/files/firefly-iii/data-importer.conf', dest: '/etc/apache2/sites-available/data-importer.conf' }

    - name: Enable Apache sites
      command: a2ensite firefly-iii.conf data-importer.conf

    - name: Configure PHP modules
      shell: |
        a2dismod php7.4
        a2enmod php8.2
        a2enmod rewrite

    - name: Restart Apache server
      command: service apache2 restart
