---
- name: Install and configure MySQL 8
  hosts: db_instance
  become: yes
  vars_files:
    - "{{playbook_dir}}/variables/db.yml"

  pre_tasks:
    - name: Make sure Python and pip are installed
      apt:
        update_cache: yes
        name:
          - python3
          - python3-pip

    - name: Make sure pymysql is present
      pip:
        name: pymysql
        state: present

    - name: Allow HTTP traffic through firewall
      shell: |
        iptables -A INPUT -p tcp --dport 3306 -j ACCEPT
        netfilter-persistent save
        netfilter-persistent reload
        iptables -F

  tasks:
    - name: Install MySQL 8 repository
      apt:
        name: software-properties-common
        state: present

    - name: Import MySQL GPG Key
      apt_key:
        url: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
        state: present

    - name: Add MySQL APT repository
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/ubuntu/ {{ ansible_distribution_release }} mysql-8.0"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Remove anonymous MySQL user
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: ''
        state: absent

    - name: Remove test MySQL database
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: test
        state: absent

    - name: Create the Firefly database
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: firefly

    - name: Create MySQL user with all privileges
      community.mysql.mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: 'firefly'
        password: '{{ db_user_password }}'
        host: base-vm.basesubnet.basevcn.oraclevcn.com
        priv: 'firefly.*:ALL'
        state: present
      when: db_user_password is defined

    - name: Reload privilege tables
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False
